language: node_js

os:
  - linux
  - osx

node_js:
  - 8.11.2

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - npm i -g npm@6.0.1
  - npm install gulp -g

script:
  - gulp release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gulp release --chromeos; fi

cache:
  directories:
  - node_modules
