language: node_js

os:
  - linux
  - osx

node_js:
  - node

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - npm i -g npm@latest
  - npm install gulp -g

script:
  - npm install
  - gulp release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gulp release --chromeos; fi

cache:
  directories:
  - node_modules
